# enable 256 colors
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
# change default prefix key
set -g prefix C-Space
unbind C-b
# enable mouse support
set -g mouse on
# not sure why these are in here. scrolling?
unbind-key C-pageup
unbind-key C-pagedown
